---
title: "Texas Water Governance - Static Networks"
author: "Ethan"
date: "2/10/2021"
output: html_document
---

```{r include=FALSE}
source("utils1.R")

packages = c('tidygraph', 'ggraph', 'visNetwork', 'lubridate', 'tidyverse')

for(p in packages){library
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```

```{r Clean Network Data, include=FALSE}

#edgelist 
el1<-el1
e1<-as.matrix(el1)
e1[,1]=as.character(e1[,1])
e1[,2]=as.character(e1[,2])
e1[,3]=as.character(e1[,3])
e1[,4]=as.character(e1[,4])
e1[,5]=as.character(e1[,5])

#Edge Colors
edge_colors <- 
  c(
      "#fb7e81",# "Advocacy/Policy Preference",
      "#ffa807",#   "Information",
      "red",#   "Authority to set rules",
      "black",#   "Contract",
      "#eb7df4",#   "Cooperation/coordination",
      "#97c2fc",#   "Water",                      
      "#006200",#   "Regulation/Oversight",
      "#7be141",#   "Money",
      "#0000CD",#   "Lobbying",
      "#ad85e4", #   "Membership",
      "#049E8E",#   "Water sales,
      "gray"
  )


names(edge_colors) <- c(
    "Advocacy/Policy Preference",
    "Information",
    "Authority to set rules",
    "Contract",
    "Cooperation/coordination",
    "Water",                      
    "Regulation/Oversight",
    "Money",
    "Lobbying",
    "Membership",
    "Water sales"
)


#Node Colors
node_colors <- c("#fb7e81",
                    "#ad85e4",
                    "#7be141",
                    "#ffa807",
                    "#0000CD",
                    "#97c2fc",
                    "#eb7df4")


names(node_colors) <- c(
  "Public",
  "Government",
  "Utilities",
  "Academic",
  "NGO",
  "Physical Feature",
  "Private"
)

node_color_order <- c(
  "Public",
  "Government",
  "Utilities",
  "Academic",
  "NGO",
  "Physical Feature",
  "Private"
)


for (i in 1:length(el1$type)){
  if (any(names(edge_colors) %in% el1$type[i]) == FALSE){
    el1$type[i] <- "Other"
  }
}


g1<-graph_from_data_frame(d=el1,directed=TRUE) 
#Some stats like communities and clusters need undirected graphs. Mode = collapse creates an undirected link between any pair of connected nodes. 
#g1<-as.undirected(g1, mode= "collapse")

#Create a nodelist for excel use 
gvis<-toVisNetworkData(g1)
nodelist<-gvis$nodes
nodelist<-nodelist[,1]
nodelist<-as.data.frame(nodelist)
names(nodelist)<-c("name")

write.csv(nodelist,file = "nodelist.csv")

# Pull the node list with attributes
input_attributes<-a1

#Define Attributes
for (i in 1:vcount(g1))
{
V(g1)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1)[i]$name)]
V(g1)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1)[i]$name)]
V(g1)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1)[i]$name)]
}

####Agriculture####
#new dataframe and igraph object with only "agriculture" ties
el1_agriculture<-el1[which(el1$sector=="Agriculture"),]
g1_agriculture<-graph_from_data_frame(d=el1_agriculture,directed=TRUE) 
e1_agriculture<-as.matrix(el1_agriculture)

####Groundwater####
#new dataframe and igraph object with only "Groundwater" ties
el1_groundwater<-el1[which(el1$sector=="Groundwater"),]
g1_groundwater<-graph_from_data_frame(d=el1_groundwater,directed=TRUE) 
e1_groundwater<-as.matrix(el1_groundwater)

####Oil and Gas####
#new dataframe and igraph object with only "Oil and Gas" ties
el1_oilandgas<-el1[which(el1$sector=="Oil and Gas"),]
g1_oilandgas<-graph_from_data_frame(d=el1_oilandgas,directed=TRUE) 
e1_oilandgas<-as.matrix(el1_oilandgas)

####flooding####
#new dataframe and igraph object with only "flooding" ties
el1_flooding<-el1[which(el1$sector=="Flooding"),]
g1_flooding<-graph_from_data_frame(d=el1_flooding,directed=TRUE) 
e1_flooding<-as.matrix(el1_flooding)

####rural####
#new dataframe and igraph object with only "rural" ties
el1_rural<-el1[which(el1$sector=="Rural Utilities"),]
g1_rural<-graph_from_data_frame(d=el1_rural,directed=TRUE) 
e1_rural<-as.matrix(el1_rural)

####environment####
#new dataframe and igraph object with only "environment" ties
el1_environment<-el1[which(el1$sector=="Environment"),]
g1_environment<-graph_from_data_frame(d=el1_environment,directed=TRUE) 
e1_environment<-as.matrix(el1_environment)

####innovation####
#new dataframe and igraph object with only "innovation" ties
el1_innovation<-el1[which(el1$sector=="Innovation"),]
g1_innovation<-graph_from_data_frame(d=el1_innovation,directed=TRUE) 
e1_innovation<-as.matrix(el1_innovation)

####municipal####
#new dataframe and igraph object with only "municipal" ties
el1_municipal<-el1[which(el1$sector=="Municipal"),]
g1_municipal<-graph_from_data_frame(d=el1_municipal,directed=TRUE) 
e1_municipal<-as.matrix(el1_municipal)


names(edge_colors) <- c(
    "Advocacy/Policy Preference",
    "Information",
    "Authority to set rules",
    "Contract",
    "Cooperation/coordination",
    "Water",                      
    "Regulation/Oversight",
    "Money",
    "Lobbying",
    "Membership",
    "Water sales",
    "Other"
)


edge_color_order = c(
  "Information",
  "Advocacy/Policy Preference",
  "Authority to set rules",
  "Cooperation/coordination",
  "Membership",
  "Lobbying",
  "Water",
  "Water sales",
  "Regulation/Oversight",
  "Money",
  "Contract",
  "Other"
)


```

$~$

## Ego-centric Network Measures
```{r network statistics, include = FALSE, echo=FALSE, warning=FALSE}
#Degree in 
inDegree<-igraph::degree(g1,mode="in")
outDegree<-igraph::degree(g1,mode="out")
TotalDegree<-as.data.frame(igraph::degree(g1))
betweenness<-igraph::betweenness(g1, v = V(g1), directed = TRUE, weights = NULL,
  nobigint = TRUE, normalized = TRUE)
inCloseness<-igraph::closeness(g1, vids = V(g1), mode = c("in"),normalized = TRUE)
outCloseness<-igraph::closeness(g1, vids = V(g1), mode = c("out"),normalized = TRUE)
#eigen<-evcent(m1,g=1,gmode = "digraph",rescale=TRUE, ignore.eval=TRUE)
#removed eigen from this DF_Centrality
DF_Centrality<-as.data.frame(cbind(rownames(TotalDegree),inDegree,outDegree,TotalDegree,betweenness,inCloseness,outCloseness))
rownames(DF_Centrality)<-NULL
DF_Centrality<-as.data.frame(DF_Centrality)
colnames(DF_Centrality)[1]<-"name"
colnames(DF_Centrality)[4]<-"TotalDegree"


# par(mfcol = c(4,3)) 
# hist(inDegree)
# hist(outDegree)
# hist(TotalDegree)
# hist(betweenness)
# hist(inCloseness)
# hist(outCloseness)

dd.g1<-degree.distribution(g1)
d<-1:max(TotalDegree)-1
ind<-(dd.g1 != 0)
plot(d[ind],dd.g1[ind],log="xy",col="blue",xlab=c("Log-degree"),ylab=c("Log-Intensity"),
     main="Log-Log Degree Distribution")

txwater_centrality<-merge(DF_Centrality, a1, by = "name")
write.csv(txwater_centrality,file = "TX Water Centrality.csv")

input_attributes<-txwater_centrality

```


## Full Network (Node Focused)

```{r ggplot, message=FALSE, warning=FALSE}
library(extrafont)
loadfonts()

set.seed(27)

nodes <- sort(gvis_ext$nodes)
nodes$size <- nodes$size*5
edges <- gvis_ext$edges






for (i in 1:length(edges$type)){
  if (any(names(edge_colors) %in% edges$type[i]) == FALSE){
    edges$type[i] <- "Other"
  }
}


graph <- graph_from_data_frame(vertices = nodes, d = edges, directed = TRUE)


g <- ggraph(graph, layout = 'stress') +
  geom_edge_link(
    aes(edge_color = "#049E8E"),
    edge_width = 1,
    edge_alpha = 0.6
  ) +
  geom_node_point(aes(size = size * 10, color = type)) +
  geom_node_text(
     aes(
       x = x,
       y = y - .2,
       size = 500,
       label = ifelse(
         size > 100, 
         label, 
         ""))
     ) +
  scale_color_manual(name = "Type of Organization", values = node_colors, breaks = node_color_order) +
  scale_edge_color_manual(values = "#049E8E") +
  scale_size_area(max_size = 10) +
  theme_graph(title_size = 34) +
  labs(title = 'Policy and Governance across Texas Water Sector') +
  theme(
    text = element_text('Helvetica', size = 20),
    plot.title = element_text(
      face = 'bold',
      hjust = 0.5,
      margin = margin(t = 45, b = 3)
    ),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  guides(size = "none",
         color = guide_legend(override.aes = list(size = 5)),
         edge_color = "none")


g

ggsave(
  'media/all_network_node_focused.png',
  width = 16,
  height = 12,
  dpi = 500
)

```
## Full network (Edge Focused)
```{r fullnetwork_edges, message=FALSE, warning=FALSE}
set.seed(27)


g <- ggraph(graph, layout = 'stress') +
  geom_edge_link(aes(edge_color = type),
                 edge_width = 1,
                 edge_alpha = 0.7) +
  geom_node_point(aes(
    size = size * 5,
    color = "black",
    shape = level,
    alpha = 0.5
  )) +
  geom_node_text(aes(
    x = x,
    y = y - .2,
    size = 500,
    label = ifelse(size > 100,
                   label,
                   "")
  )) +
  scale_color_manual(values = "black") +
  scale_shape_discrete(name = "Area of Operation") +
  scale_edge_color_manual(name = "Connection Type", values = edge_colors, breaks = edge_color_order) +
  scale_size_area(max_size = 10) +
  scale_shape_manual(values=c(18,16,17,15))+
  theme_graph(title_size = 34) +
  labs(title = 'Policy and Governance across Texas Water Sector') +
  theme(
    text = element_text('Helvetica', size = 20),
    plot.title = element_text(
      face = 'bold',
      hjust = 0.5,
      margin = margin(t = 45, b = 3)
    ),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  guides(
    size = "none",
    color = "none",
    edge_color = guide_legend(override.aes = list(size = 5)),
    shape = guide_legend(override.aes = list(size = 5), title = "Area of Operation"),
    alpha = "none"
  )


g

ggsave(
  'media/all_network_edge_focused.png',
  width = 16,
  height = 12,
  dpi = 500
)


```

## Agriculture

```{r agriculture, message=FALSE, warning=FALSE}

for (i in 1:vcount(g1_agriculture))
{
V(g1_agriculture)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_agriculture)[i]$name)]
V(g1_agriculture)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_agriculture)[i]$name)]
V(g1_agriculture)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_agriculture)[i]$name)]
V(g1_agriculture)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_agriculture)[i]$name)]
}


V(g1_agriculture)[which(V(g1_agriculture)$level=="Local")]$shape<-"dot"
V(g1_agriculture)[which(V(g1_agriculture)$level=="Regional")]$shape<-"triangle"
V(g1_agriculture)[which(V(g1_agriculture)$level=="Statewide")]$shape<-"square"


g <- ggraph(g1_agriculture, layout = 'fr') +
  geom_edge_link(
    aes(edge_color = node1.type),
    edge_width = 1,
    edge_alpha = 0.6,
    arrow = arrow(length = unit(4, 'mm')),
    end_cap = circle(3, 'mm')
  ) +
  geom_node_point(aes(
    size = size * 10,
    color = type,
    shape = level
  )) +
  geom_node_text(aes(x = x,
                     y = y - .1,
                     label = label)) +
  scale_color_manual(name = "Type of Organization", values = node_colors) +
  scale_edge_color_manual(name = "Type of Connection", values = node_colors) +
  scale_size_area(max_size = 10) +
  theme_graph(title_size = 34) +
  labs(title = 'Agriculture') +
  theme(
    text = element_text('Helvetica', size = 24),
    plot.title = element_text(
      face = 'bold',
      hjust = 0.5,
      margin = margin(t = 45, b = 3)
    ),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  guides(
    size = "none",
    color = guide_legend(override.aes = list(size = 5)),
    edge_color = "none",
    shape = guide_legend(override.aes = list(size = 5))
  )


g

ggsave(
  'media/agriculture.png',
  width = 16,
  height = 12,
  dpi = 500
)




```

# Environment 


```{r environment, message=FALSE, warning=FALSE}

#Define Attributes
for (i in 1:vcount(g1_environment))
{
V(g1_environment)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_environment)[i]$name)]
V(g1_environment)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_environment)[i]$name)]
V(g1_environment)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_environment)[i]$name)]
V(g1_environment)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_environment)[i]$name)]
}

V(g1_environment)[which(V(g1_environment)$level=="Local")]$shape<-"dot"
V(g1_environment)[which(V(g1_environment)$level=="Regional")]$shape<-"triangle"
V(g1_environment)[which(V(g1_environment)$level=="Statewide")]$shape<-"square"


g <- ggraph(g1_environment, layout = 'fr') +
  geom_edge_link(
    aes(edge_color = node1.type),
    edge_width = 1,
    edge_alpha = 0.6,
    arrow = arrow(length = unit(4, 'mm')),
    end_cap = circle(3, 'mm')
  ) +
  geom_node_point(aes(
    size = size * 10,
    color = type,
    shape = level
  )) +
  geom_node_text(aes(x = x,
                     y = y - .1,
                     label = label)) +
  scale_color_manual(name = "Type of Organization", values = node_colors) +
  scale_edge_color_manual(name = "Type of Connection", values = node_colors) +
  scale_shape_manual(values=c(18,16,17,15))+
  scale_size_area(max_size = 10) +
  theme_graph(title_size = 34) +
  labs(title = 'Environment') +
  theme(
    text = element_text('Helvetica', size = 24),
    plot.title = element_text(
      face = 'bold',
      hjust = 0.5,
      margin = margin(t = 45, b = 3)
    ),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  guides(
    size = "none",
    color = guide_legend(override.aes = list(size = 5)),
    edge_color = "none",
    shape = guide_legend(override.aes = list(size = 5))
  )


g

ggsave(
  'media/environment.png',
  width = 16,
  height = 12,
  dpi = 500
)


```

# Flooding

```{r environment, message=FALSE, warning=FALSE}

#Define Attributes
for (i in 1:vcount(g1_flooding))
{
V(g1_flooding)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_flooding)[i]$name)]
V(g1_flooding)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_flooding)[i]$name)]
V(g1_flooding)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_flooding)[i]$name)]
V(g1_flooding)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_flooding)[i]$name)]
}


g <- ggraph(g1_flooding, layout = 'fr') +
  geom_edge_link(
    aes(edge_color = node1.type),
    edge_width = 1,
    edge_alpha = 0.6,
    arrow = arrow(length = unit(4, 'mm')),
    end_cap = circle(3, 'mm')
  ) +
  geom_node_point(aes(
    size = size * 20,
    color = type,
    shape = level
  )) +
  geom_node_text(aes(x = x,
                     y = y - .1,
                     label = label)) +
  scale_color_manual(name = "Type of Organization", values = node_colors) +
  scale_edge_color_manual(name = "Type of Connection", values = node_colors) +
  scale_shape_manual(values=c(16,17,15))+
  scale_size_area(max_size = 10) +
  theme_graph(title_size = 34) +
  labs(title = 'Flooding') +
  theme(
    text = element_text('Helvetica', size = 24),
    plot.title = element_text(
      face = 'bold',
      hjust = 0.5,
      margin = margin(t = 45, b = 3)
    ),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  guides(
    size = "none",
    color = guide_legend(override.aes = list(size = 5)),
    edge_color = "none",
    shape = guide_legend(override.aes = list(size = 5))
  )


g

ggsave(
  'media/flooding.png',
  width = 16,
  height = 12,
  dpi = 500
)


```
## Groundwater


```{r environment, message=FALSE, warning=FALSE}

#Define Attributes
for (i in 1:vcount(g1_groundwater))
{
V(g1_groundwater)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_groundwater)[i]$name)]
V(g1_groundwater)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_groundwater)[i]$name)]
V(g1_groundwater)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_groundwater)[i]$name)]
V(g1_groundwater)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_groundwater)[i]$name)]
}


g <- ggraph(g1_groundwater, layout = 'fr') +
  geom_edge_link(
    aes(edge_color = node1.type),
    edge_width = 1,
    edge_alpha = 0.6,
    arrow = arrow(length = unit(4, 'mm')),
    end_cap = circle(3, 'mm')
  ) +
  geom_node_point(aes(
    size = size * 10,
    color = type,
    shape = level
  )) +
  geom_node_text(aes(x = x,
                     y = y - .1,
                     label = label)) +
  scale_color_manual(name = "Type of Organization", values = node_colors) +
  scale_edge_color_manual(name = "Type of Connection", values = node_colors) +
  scale_shape_manual(values=c(16,17,15))+
  scale_size_area(max_size = 10) +
  theme_graph(title_size = 34) +
  labs(title = 'Groundwater') +
  theme(
    text = element_text('Helvetica', size = 24),
    plot.title = element_text(
      face = 'bold',
      hjust = 0.5,
      margin = margin(t = 45, b = 3)
    ),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  guides(
    size = "none",
    color = guide_legend(override.aes = list(size = 5)),
    edge_color = "none",
    shape = guide_legend(override.aes = list(size = 5))
  )


g

ggsave(
  'media/groundwater.png',
  width = 16,
  height = 12,
  dpi = 500
)


```
## Innovation


```{r environment, message=FALSE, warning=FALSE}

#Define Attributes
for (i in 1:vcount(g1_innovation))
{
V(g1_innovation)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_innovation)[i]$name)]
V(g1_innovation)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_innovation)[i]$name)]
V(g1_innovation)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_innovation)[i]$name)]
V(g1_innovation)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_innovation)[i]$name)]
}


g <- ggraph(g1_innovation, layout = 'fr') +
  geom_edge_link(
    aes(edge_color = node1.type),
    edge_width = 1,
    edge_alpha = 0.6,
    arrow = arrow(length = unit(4, 'mm')),
    end_cap = circle(3, 'mm')
  ) +
  geom_node_point(aes(
    size = size * 20,
    color = type,
    shape = level
  )) +
  geom_node_text(aes(x = x,
                     y = y - .1,
                     label = label)) +
  scale_color_manual(name = "Type of Organization", values = node_colors) +
  scale_edge_color_manual(name = "Type of Connection", values = node_colors) +
  scale_shape_manual(values=c(18,16,17,15))+
  scale_size_area(max_size = 10) +
  theme_graph(title_size = 34) +
  labs(title = 'Innovation') +
  theme(
    text = element_text('Helvetica', size = 24),
    plot.title = element_text(
      face = 'bold',
      hjust = 0.5,
      margin = margin(t = 45, b = 3)
    ),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  guides(
    size = "none",
    color = guide_legend(override.aes = list(size = 5)),
    edge_color = "none",
    shape = guide_legend(override.aes = list(size = 5))
  )


g

ggsave(
  'media/innovation.png',
  width = 16,
  height = 12,
  dpi = 500
)


```


## Municipal


```{r environment, message=FALSE, warning=FALSE}

#Define Attributes
for (i in 1:vcount(g1_municipal))
{
V(g1_municipal)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_municipal)[i]$name)]
V(g1_municipal)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_municipal)[i]$name)]
V(g1_municipal)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_municipal)[i]$name)]
V(g1_municipal)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_municipal)[i]$name)]
}


g <- ggraph(g1_municipal, layout = 'fr') +
  geom_edge_link(
    aes(edge_color = node1.type),
    edge_width = 1,
    edge_alpha = 0.6,
    arrow = arrow(length = unit(4, 'mm')),
    end_cap = circle(3, 'mm')
  ) +
  geom_node_point(aes(
    size = size * 20,
    color = type,
    shape = level
  )) +
  geom_node_text(aes(x = x,
                     y = y - .1,
                     label = label)) +
  scale_color_manual(name = "Type of Organization", values = node_colors) +
  scale_edge_color_manual(name = "Type of Connection", values = node_colors) +
  scale_shape_manual(values=c(16,17,15))+
  scale_size_area(max_size = 10) +
  theme_graph(title_size = 34) +
  labs(title = 'Municipal') +
  theme(
    text = element_text('Helvetica', size = 24),
    plot.title = element_text(
      face = 'bold',
      hjust = 0.5,
      margin = margin(t = 45, b = 3)
    ),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  guides(
    size = "none",
    color = guide_legend(override.aes = list(size = 5)),
    edge_color = "none",
    shape = guide_legend(override.aes = list(size = 5))
  )


g

ggsave(
  'media/municipal.png',
  width = 16,
  height = 12,
  dpi = 500
)


```

## Oil and Gas

```{r environment, message=FALSE, warning=FALSE}

#Define Attributes
for (i in 1:vcount(g1_oilandgas))
{
V(g1_oilandgas)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_oilandgas)[i]$name)]
V(g1_oilandgas)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_oilandgas)[i]$name)]
V(g1_oilandgas)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_oilandgas)[i]$name)]
V(g1_oilandgas)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_oilandgas)[i]$name)]
}


g <- ggraph(g1_oilandgas, layout = 'fr') +
  geom_edge_link(
    aes(edge_color = node1.type),
    edge_width = 1,
    edge_alpha = 0.6,
    arrow = arrow(length = unit(4, 'mm')),
    end_cap = circle(3, 'mm')
  ) +
  geom_node_point(aes(
    size = size * 20,
    color = type,
    shape = level
  )) +
  geom_node_text(aes(x = x,
                     y = y - .1,
                     label = label)) +
  scale_color_manual(name = "Type of Organization", values = node_colors) +
  scale_edge_color_manual(name = "Type of Connection", values = node_colors) +
  scale_shape_manual(values=c(16,17,15))+
  scale_size_area(max_size = 10) +
  theme_graph(title_size = 34) +
  labs(title = 'Oil and Gas') +
  theme(
    text = element_text('Helvetica', size = 24),
    plot.title = element_text(
      face = 'bold',
      hjust = 0.5,
      margin = margin(t = 45, b = 3)
    ),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  guides(
    size = "none",
    color = guide_legend(override.aes = list(size = 5)),
    edge_color = "none",
    shape = guide_legend(override.aes = list(size = 5))
  )


g

ggsave(
  'media/oilandgas.png',
  width = 16,
  height = 12,
  dpi = 500
)


```


## Rural Water

```{r environment, message=FALSE, warning=FALSE}

#Define Attributes
for (i in 1:vcount(g1_rural))
{
V(g1_rural)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_rural)[i]$name)]
V(g1_rural)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_rural)[i]$name)]
V(g1_rural)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_rural)[i]$name)]
V(g1_rural)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_rural)[i]$name)]
}


g <- ggraph(g1_rural, layout = 'fr') +
  geom_edge_link(
    aes(edge_color = node1.type),
    edge_width = 1,
    edge_alpha = 0.6,
    arrow = arrow(length = unit(4, 'mm')),
    end_cap = circle(3, 'mm')
  ) +
  geom_node_point(aes(
    size = size * 20,
    color = type,
    shape = level
  )) +
  geom_node_text(aes(x = x,
                     y = y - .1,
                     label = label)) +
  scale_color_manual(name = "Type of Organization", values = node_colors) +
  scale_edge_color_manual(name = "Type of Connection", values = node_colors) +
  scale_shape_manual(values=c(18,16,17,15))+
  scale_size_area(max_size = 10) +
  theme_graph(title_size = 34) +
  labs(title = 'Rural') +
  theme(
    text = element_text('Helvetica', size = 24),
    plot.title = element_text(
      face = 'bold',
      hjust = 0.5,
      margin = margin(t = 45, b = 3)
    ),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  guides(
    size = "none",
    color = guide_legend(override.aes = list(size = 5)),
    edge_color = "none",
    shape = guide_legend(override.aes = list(size = 5))
  )


g

ggsave(
  'media/rural.png',
  width = 16,
  height = 12,
  dpi = 500
)


```