---
title: "Texas Water Governance System Mapping "
author: "Patrick Bixler"
date: "01/13/2021"
output: html_document
---

```{r include=FALSE}
source("utils1.R")
```

```{r Clean Network Data, include=FALSE}

#edgelist 
el1<-el1
e1<-as.matrix(el1)
e1[,1]=as.character(e1[,1])
e1[,2]=as.character(e1[,2])
e1[,3]=as.character(e1[,3])
e1[,4]=as.character(e1[,4])
e1[,5]=as.character(e1[,5])

g1<-graph_from_data_frame(d=el1,directed=TRUE) 
#Some stats like communities and clusters need undirected graphs. Mode = collapse creates an undirected link between any pair of connected nodes. 
#g1<-as.undirected(g1, mode= "collapse")

#Create a nodelist for excel use 
gvis<-toVisNetworkData(g1)
nodelist<-gvis$nodes
nodelist<-nodelist[,1]
nodelist<-as.data.frame(nodelist)
names(nodelist)<-c("name")

write.csv(nodelist,file = "nodelist.csv")

# Pull the node list with attributes
input_attributes<-a1

#Define Attributes
for (i in 1:vcount(g1))
{
V(g1)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1)[i]$name)]
V(g1)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1)[i]$name)]
V(g1)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1)[i]$name)]
}

####Agriculture####
#new dataframe and igraph object with only "agriculture" ties
el1_agriculture<-el1[which(el1$sector=="Agriculture"),]
g1_agriculture<-graph_from_data_frame(d=el1_agriculture,directed=TRUE) 
e1_agriculture<-as.matrix(el1_agriculture)

####Groundwater####
#new dataframe and igraph object with only "Groundwater" ties
el1_groundwater<-el1[which(el1$sector=="Groundwater"),]
g1_groundwater<-graph_from_data_frame(d=el1_groundwater,directed=TRUE) 
e1_groundwater<-as.matrix(el1_groundwater)

####Oil and Gas####
#new dataframe and igraph object with only "Oil and Gas" ties
el1_oilandgas<-el1[which(el1$sector=="Oil and Gas"),]
g1_oilandgas<-graph_from_data_frame(d=el1_oilandgas,directed=TRUE) 
e1_oilandgas<-as.matrix(el1_oilandgas)

####flooding####
#new dataframe and igraph object with only "flooding" ties
el1_flooding<-el1[which(el1$sector=="Flooding"),]
g1_flooding<-graph_from_data_frame(d=el1_flooding,directed=TRUE) 
e1_flooding<-as.matrix(el1_flooding)

####rural####
#new dataframe and igraph object with only "rural" ties
el1_rural<-el1[which(el1$sector=="Rural Utilities"),]
g1_rural<-graph_from_data_frame(d=el1_rural,directed=TRUE) 
e1_rural<-as.matrix(el1_rural)

####environment####
#new dataframe and igraph object with only "environment" ties
el1_environment<-el1[which(el1$sector=="Environment"),]
g1_environment<-graph_from_data_frame(d=el1_environment,directed=TRUE) 
e1_environment<-as.matrix(el1_environment)

```

$~$

## Ego-centric Network Measures
```{r network statistics, include = FALSE, echo=FALSE, warning=FALSE}
#Degree in 
inDegree<-igraph::degree(g1,mode="in")
outDegree<-igraph::degree(g1,mode="out")
TotalDegree<-as.data.frame(igraph::degree(g1))
betweenness<-igraph::betweenness(g1, v = V(g1), directed = TRUE, weights = NULL,
  nobigint = TRUE, normalized = TRUE)
inCloseness<-igraph::closeness(g1, vids = V(g1), mode = c("in"),normalized = TRUE)
outCloseness<-igraph::closeness(g1, vids = V(g1), mode = c("out"),normalized = TRUE)
#eigen<-evcent(m1,g=1,gmode = "digraph",rescale=TRUE, ignore.eval=TRUE)
#removed eigen from this DF_Centrality
DF_Centrality<-as.data.frame(cbind(rownames(TotalDegree),inDegree,outDegree,TotalDegree,betweenness,inCloseness,outCloseness))
rownames(DF_Centrality)<-NULL
DF_Centrality<-as.data.frame(DF_Centrality)
colnames(DF_Centrality)[1]<-"name"
colnames(DF_Centrality)[4]<-"TotalDegree"


par(mfcol = c(4,3)) 
hist(inDegree)
hist(outDegree)
hist(TotalDegree)
hist(betweenness)
hist(inCloseness)
hist(outCloseness)

dd.g1<-degree.distribution(g1)
d<-1:max(TotalDegree)-1
ind<-(dd.g1 != 0)
plot(d[ind],dd.g1[ind],log="xy",col="blue",xlab=c("Log-degree"),ylab=c("Log-Intensity"),
     main="Log-Log Degree Distribution")

txwater_centrality<-merge(DF_Centrality, a1, by = "name")
write.csv(txwater_centrality,file = "TX Water Centrality.csv")

input_attributes<-txwater_centrality

```
System Map Graphs 

#All relationships Edges Highlighted 
```{r echo=FALSE}
nodes<- read_csv("node_coords.csv")
nodes <- select(nodes, -c(X1))
nodes <- select(nodes, id, x, y)
row.names(nodes) <- nodes[['id']]

#node attributes
for (i in 1:vcount(g1))
{
V(g1)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1)[i]$name)]
V(g1)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1)[i]$name)]
V(g1)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1)[i]$name)]
V(g1)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1)[i]$name)]
}

V(g1)$size<-V(g1)$size*1.5

ledges <-
  data.frame(
    label = c(
      "Agriculture",
      "Environment",
      "Flooding",
      "Groundwater",
      "Oil and Gas",
      "Rural",
      "Municipal",
      "Innovation"
    ),
    color = c("brown", "green", "darkred", "orange", "red", "blue", "purple","yellow"),
    shape = c("line", "line", "line", "line", "line", "line","line","line")
  )

lnodes <-
  data.frame(
    label = c(
      "Agriculture",
      "Environment",
      "Flooding",
      "Groundwater",
      "Oil and Gas",
      "Rural",
      "Municipal",
      "Innovation"
    ),
    color.background = c("brown", "green", "darkred", "orange", "red", "blue", "purple","yellow"),
    color.border = c("black", "black", "black", "black", "black", "black", "black", "black"),
    shape = c("line", "line", "line", "line", "line", "line","line","line")
  )

E(g1)[E(g1)$sector=="Agriculture"]$color <-"brown"
E(g1)[E(g1)$sector=="Environment"]$color <-"green"
E(g1)[E(g1)$sector=="Flooding"]$color <-"darkred"
E(g1)[E(g1)$sector=="Groundwater"]$color <-"orange"
E(g1)[E(g1)$sector=="Oil and Gas"]$color <-"red"
E(g1)[E(g1)$sector=="Rural Utilities"]$color <-"blue"
E(g1)[E(g1)$sector=="Municipal"]$color <-"purple"
E(g1)[E(g1)$sector=="Innovation"]$color <-"yellow"
E(g1)[E(g1)$sector==""]$color <-"pink"


gvis<-toVisNetworkData(g1)
nodelist<-gvis$nodes

nodes2 <- sort(gvis$nodes)
colors <- c("#999999", "#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#b19cd9")

nodes2$color <- ""
nodes2$color[nodes2$type == "Academic"] <- colors[1]
nodes2$color[nodes2$type == "Public"] <- colors[2]
nodes2$color[nodes2$type == "Private"] <- colors[3]
nodes2$color[nodes2$type == "Physical Feature"] <- colors[4]
nodes2$color[nodes2$type == "Government"] <- colors[5]
nodes2$color[nodes2$type == "NGO"] <- colors[6]
nodes2$color[nodes2$type == "Utilities"] <- colors[7]

edges <- gvis$edges
edges$shape <- "line"
edges$label <- edges$sector

viz_all <- visNetwork(nodes2,gvis$edges,main="All Connections",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 123) %>%
  visEdges(smooth =T,
           arrows =list(to = list(enabled = TRUE, scaleFactor = .5)),
           color = list(highlight = "black"))  %>% #https://datastorm-open.github.io/visNetwork/edges.html
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE, layout="layout_with_fr", layoutMatrix = gcoords) %>%
  visLayout(randomSeed=123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left",addNodes = lnodes, addEdges = ledges , useGroups = FALSE,stepY=100)

viz_all$x$nodes <- viz_all$x$nodes %>% left_join(nodes, by = 'id') %>% select(-c('x.x', 'y.x')) %>% rename(x = x.y, y=y.y)

viz_all
```


#All network (Node emphasis)


#Network with only agriculture ties
```{r echo=FALSE}

#Define Attributes
for (i in 1:vcount(g1_agriculture))
{
V(g1_agriculture)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_agriculture)[i]$name)]
V(g1_agriculture)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_agriculture)[i]$name)]
V(g1_agriculture)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_agriculture)[i]$name)]
V(g1_agriculture)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_agriculture)[i]$name)]
}

V(g1_agriculture)$size<-V(g1_agriculture)$size/4

# E(g1_agriculture)[E(g1_agriculture)$type=="Advocacy/Policy Preference"]$color <-"brown"
# E(g1_agriculture)[E(g1_agriculture)$type==" Water sales"]$color <-"green"
# E(g1_agriculture)[E(g1_agriculture)$type=="Water rights/regulation of"]$color <-"darkred"
# E(g1_agriculture)[E(g1_agriculture)$type=="Lobbying"]$color <-"orange"
# E(g1_agriculture)[E(g1_agriculture)$type=="Membership"]$color <-"red"
# E(g1_agriculture)[E(g1_agriculture)$type=="Permits/Authorization"]$color <-"blue"


gvis_agriculture<-toVisNetworkData(g1_agriculture)
nodelist_agriclulture<-gvis_agriculture$nodes
viz_ag <- visNetwork(sort(gvis_agriculture$nodes),gvis_agriculture$edges, main="Agriculture",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 123) %>%
  visEdges(smooth =T,
           arrows =list(to = list(enabled = TRUE, scaleFactor = .1)),
           color = list(color = "lightblue", highlight = "black"))  %>% #https://datastorm-open.github.io/visNetwork/edges.html
  visNodes(font = list(size = 6)) %>% 
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE, layout="layout_with_fr") %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left", useGroups = FALSE,stepY=100)

viz_ag$x$nodes <- viz_ag$x$nodes %>% left_join(nodes, by = 'id') %>% select(-c('x.x', 'y.x')) %>% rename(x = x.y, y=y.y)

viz_ag

```

#Network with only groundwater ties
```{r echo=FALSE}

#Define Attributes
for (i in 1:vcount(g1_groundwater))
{
V(g1_groundwater)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_groundwater)[i]$name)]
V(g1_groundwater)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_groundwater)[i]$name)]
V(g1_groundwater)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_groundwater)[i]$name)]
V(g1_groundwater)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_groundwater)[i]$name)]
}

V(g1_groundwater)$size<-V(g1_groundwater)$size/4

gvis_groundwater<-toVisNetworkData(g1_groundwater)
nodelist_agriclulture<-gvis_groundwater$nodes
viz_groundwater <- visNetwork(sort(gvis_groundwater$nodes),gvis_groundwater$edges, main="Groundwater",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 123) %>%
  visEdges(smooth =T,
           arrows =list(to = list(enabled = TRUE, scaleFactor = .1)),
           color = list(color = "lightblue", highlight = "black"))  %>% #https://datastorm-open.github.io/visNetwork/edges.html
  visNodes(font = list(size = 6)) %>% 
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE, layout="layout_with_fr") %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left", useGroups = FALSE,stepY=100)

viz_groundwater$x$nodes <- viz_groundwater$x$nodes %>% left_join(nodes, by = 'id') %>% select(-c('x.x', 'y.x')) %>% rename(x = x.y, y=y.y)

viz_groundwater
```
#Network with only environment ties
```{r echo=FALSE}

#Define Attributes
for (i in 1:vcount(g1_environment))
{
V(g1_environment)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_environment)[i]$name)]
V(g1_environment)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_environment)[i]$name)]
V(g1_environment)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_environment)[i]$name)]
V(g1_environment)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_environment)[i]$name)]
}

V(g1_environment)$size<-V(g1_environment)$size/3

gvis_environment<-toVisNetworkData(g1_environment)
nodelist_agriclulture<-gvis_environment$nodes
viz_environment <- visNetwork(sort(gvis_environment$nodes),gvis_environment$edges, main="Environment",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 123) %>%
  visEdges(smooth =T,
           arrows =list(to = list(enabled = TRUE, scaleFactor = .1)),
           color = list(color = "lightblue", highlight = "black"))  %>% #https://datastorm-open.github.io/visNetwork/edges.html
  visNodes(font = list(size = 7)) %>% 
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE, layout="layout_with_fr") %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left", useGroups = FALSE,stepY=100)

viz_environment$x$nodes <- viz_environment$x$nodes %>% left_join(nodes, by = 'id') %>% select(-c('x.x', 'y.x')) %>% rename(x = x.y, y=y.y)

viz_environment
```

#Network with only flooding ties
```{r echo=FALSE}

#Define Attributes
for (i in 1:vcount(g1_flooding))
{
V(g1_flooding)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_flooding)[i]$name)]
V(g1_flooding)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_flooding)[i]$name)]
V(g1_flooding)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_flooding)[i]$name)]
V(g1_flooding)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_flooding)[i]$name)]
}

V(g1_flooding)$size<-V(g1_flooding)$size/2.5

gvis_flooding<-toVisNetworkData(g1_flooding)
nodelist_agriclulture<-gvis_flooding$nodes
viz_flooding <- visNetwork(sort(gvis_flooding$nodes),gvis_flooding$edges, main="Flooding",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 123) %>%
  visEdges(smooth =T,
           arrows =list(to = list(enabled = TRUE, scaleFactor = .1)),
           color = list(color = "lightblue", highlight = "black"))  %>% #https://datastorm-open.github.io/visNetwork/edges.html
  visNodes(font = list(size = 10)) %>%
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE, layout="layout_with_fr") %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left", useGroups = FALSE,stepY=100)

viz_flooding$x$nodes <- viz_flooding$x$nodes %>% left_join(nodes, by = 'id') %>% select(-c('x.x', 'y.x')) %>% rename(x = x.y, y=y.y)

viz_flooding
```

#Network with only oilandgas ties
```{r echo=FALSE}

#Define Attributes
for (i in 1:vcount(g1_oilandgas))
{
V(g1_oilandgas)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_oilandgas)[i]$name)]
V(g1_oilandgas)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_oilandgas)[i]$name)]
V(g1_oilandgas)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_oilandgas)[i]$name)]
V(g1_oilandgas)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_oilandgas)[i]$name)]
}

V(g1_oilandgas)$size<-V(g1_oilandgas)$size/2.5
#Nodes with a size smaller than one can not be moved, I had to manually set the value 
V(g1_oilandgas)$size<-V(g1_oilandgas)$size + 1

gvis_oilandgas<-toVisNetworkData(g1_oilandgas)
nodelist_agriclulture<-gvis_oilandgas$nodes
viz_oil <- visNetwork(sort(gvis_oilandgas$nodes),gvis_oilandgas$edges, main="Oil and Gas",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 123) %>%
  visEdges(smooth =T,
           arrows =list(to = list(enabled = TRUE, scaleFactor = .1)),
           color = list(color = "lightblue", highlight = "black"))  %>% #https://datastorm-open.github.io/visNetwork/edges.html
  visNodes(font = list(size = 8)) %>%
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE, layout="layout_with_fr") %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left", useGroups = FALSE,stepY=100)

viz_oil$x$nodes <- viz_oil$x$nodes %>% left_join(nodes, by = 'id') %>% select(-c('x.x', 'y.x')) %>% rename(x = x.y, y=y.y)

viz_oil
```

#Network with only rural ties
```{r echo=FALSE}

#Define Attributes
for (i in 1:vcount(g1_rural))
{
V(g1_rural)[i]$label<-input_attributes$label[which(input_attributes$name==V(g1_rural)[i]$name)]
V(g1_rural)[i]$level<-input_attributes$level[which(input_attributes$name==V(g1_rural)[i]$name)]
V(g1_rural)[i]$type<-input_attributes$type[which(input_attributes$name==V(g1_rural)[i]$name)]
V(g1_rural)[i]$size<-input_attributes$TotalDegree[which(input_attributes$name==V(g1_rural)[i]$name)]
}

V(g1_rural)$size<-V(g1_rural)$size/3

gvis_rural<-toVisNetworkData(g1_rural)
nodelist_agriclulture<-gvis_rural$nodes
viz_rural <- visNetwork(sort(gvis_rural$nodes),gvis_rural$edges, main="Rural",width = "100%",height = "850px") %>%
  visLayout(randomSeed = 123) %>%
  visEdges(smooth =T,
           arrows =list(to = list(enabled = TRUE, scaleFactor = .1)),
           color = list(color = "lightblue", highlight = "black"))  %>% #https://datastorm-open.github.io/visNetwork/edges.html
  visNodes(font = list(size = 8)) %>%
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(smooth=FALSE,physics=FALSE, layout="layout_with_fr") %>%
  visLayout(randomSeed = 123,improvedLayout = TRUE)%>%
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(selectedBy = list(variable = c("program"), multiple = TRUE),
             highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = TRUE)%>%
  addFontAwesome() %>%
  visLegend(position = "left", useGroups = FALSE,stepY=100)

viz_rural$x$nodes <- viz_rural$x$nodes %>% left_join(nodes, by = 'id') %>% select(-c('x.x', 'y.x')) %>% rename(x = x.y, y=y.y)

viz_rural
```
