# load packages
library(rmarkdown)
library(igraph)
library(sna)
library(visNetwork)
library(qgraph)
library(ggplot2)
library(dplyr)
library(xtable)
library(stats)
library(car)
library(htmlwidgets)
library(htmltools)
library(rpivotTable)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(mice)
library(VIM)
library(psych)
library(semPlot)
library(lavaan)
library(kableExtra)
library(knitr)
library(ggcorrplot)
library(tidyverse)
library(openxlsx)
library(htmlTable)
library(htmlwidgets)
library(ggmap)
library(readr)
library(plotly)
library(DiagrammeR)
library(DiagrammeRsvg)
library(motifr)


#load data
el1 <-read.csv("Texas Water Network Coding.csv")
a1<-read.csv("TX Water Attributes.csv")
